name: TEST

on:
  push:
    branches: [ main ]
    
  workflow_dispatch:
  

  repository_dispatch:
    types: [ publish_blog ]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: RunAll
        run: |
            mkdir -p /home/runner/.ssh
            echo "$DEPLOY_KEY" > /home/runner/.ssh/github_actions
            chmod 600 /home/runner/.ssh/github_actions
            cat >>~/.ssh/config <<END
            Host LAD
              HostName $SSH_HOST
              User $SSH_USER
              IdentityFile ~/.ssh/github_actions
              StrictHostKeyChecking no
              HostKeyAlgorithms +ssh-dss
              HostKeyAlgorithms +ssh-rsa
              KexAlgorithms diffie-hellman-group14-sha1
              PubkeyAcceptedKeyTypes +ssh-rsa
              PubkeyAcceptedKeyTypes +ssh-dss
            END
            ssh LAD 'ls -la'
        env:
          SSH_USER: bogdani
          SSH_HOST: digilab4.let.uniroma1.it
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
