name: TEST

on:
  push:
    branches: [ main ]
    
  workflow_dispatch:
  

  repository_dispatch:
    types: [ publish_blog ]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: RunAll
        run: |
            mkdir -p /home/runner/.ssh
            echo "$DEPLOY_KEY" > /home/runner/.ssh/github_actions
            chmod 600 /home/runner/.ssh/github_actions
            cat >>~/.ssh/config <<END
            Host LAD
              HostName $SSH_HOST
              User $SSH_USER
              IdentityFile ~/.ssh/github_actions
              ssh-keyscan $SSH_HOST >> /home/runner/.ssh/known_hosts
            END
        env:
          SSH_USER: bogdani
          SSH_HOST: digilab4.let.uniroma1.it
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
      - name: View local
        run: |
          echo "github_actions contents:"
          cat /home/runner/.ssh/github_actions
          echo "known hosts:"
          cat /home/runner/.ssh/known_hosts
      - name: LS remote
        run: ssh LAD 'ls -la'
