name: Command via SSH

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Test variables
        run:|
            echo ${{ secrets.DEPLOY_KEY}} >> ciao.txt
            cat ciao.txt
        env:
          CI: true