name: TEST

on:
  push:
    branches: [ main ]
    
  workflow_dispatch:
  

  repository_dispatch:
    types: [ publish_blog ]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: RunAll
        run: |
            mkdir -p /home/runner/.ssh
            echo "$DEPLOY_KEY" > /home/runner/.ssh/github_actions
            chmod 600 /home/runner/.ssh/github_actions
            cat >>~/.ssh/config <<END
            Host LAD
              HostName $SSH_HOST
              User $SSH_USER
              IdentityFile ~/.ssh/github_actions
              StrictHostKeyChecking no
            END
        env:
          SSH_USER: ${{secrets.SSH_USER}}
          SSH_HOST: ${{secrets.SSH_HOST}}
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
      - name: List content
        run: ssh LAD 'ls -la'
